DROP TABLE  EDU  CASCADE CONSTRAINTS;
DROP TABLE  PET CASCADE CONSTRAINTS ;
DROP TABLE  MEMBER CASCADE CONSTRAINTS;
DROP TABLE  MESSAGE  CASCADE CONSTRAINTS;
DROP TABLE  PAYMENT  CASCADE CONSTRAINTS;
DROP TABLE  PREBOOKING  CASCADE CONSTRAINTS;
DROP TABLE  PREANSWER CASCADE CONSTRAINTS ;
DROP TABLE  QUESTION  CASCADE CONSTRAINTS;
DROP TABLE  ANSWER  CASCADE CONSTRAINTS;
DROP TABLE  TIPBOARD  CASCADE CONSTRAINTS;
DROP TABLE  TIPBOARD_REPLY  CASCADE CONSTRAINTS;
DROP TABLE  FREEBOARD CASCADE CONSTRAINTS ;
DROP TABLE  FREEBOARD_REPLY  CASCADE CONSTRAINTS;
DROP TABLE  MANAGER CASCADE CONSTRAINTS ;
DROP TABLE  FAQ CASCADE CONSTRAINTS ;
DROP TABLE  REPORT CASCADE CONSTRAINTS ;
DROP TABLE  NOTICE CASCADE CONSTRAINTS ;
DROP TABLE  BOOKING CASCADE CONSTRAINTS ;
DROP TABLE  REVIEW CASCADE CONSTRAINTS ;

CREATE TABLE  EDU  (
    USER_ID    VARCHAR2(100)      NOT NULL,
    EDU_YN    VARCHAR2(100)      NOT NULL,
    SITTER_YN    VARCHAR2(100)      NOT NULL
);

CREATE TABLE  PET  (
    PET_NO    NUMBER      NOT NULL,
    PET_NAME    VARCHAR2(100)      NOT NULL,
    PET_BREADS    VARCHAR2(100)      NOT NULL,
    PET_DATE    VARCHAR2(100)      NOT NULL,
    PET_SIZE    VARCHAR2(100)      NOT NULL,
    PET_GENDER    VARCHAR2(100)      NOT NULL,
    PET_NEUTRALIZE    VARCHAR2(100)      NOT NULL,
    PET_CHARATER    VARCHAR2(100)      NULL,
    USER_ID    VARCHAR2(100)      NOT NULL
);

CREATE TABLE  MEMBER  (
    USER_ID    VARCHAR2(100)      NOT NULL,
    EMAIL    VARCHAR2(100)      NULL,
    USER_NAME    VARCHAR2(100)      NULL,
    ADDRESS    VARCHAR2(100)      NULL,
    PHONE    VARCHAR2(100)      NULL,
    JOB    VARCHAR2(100)      NULL,
    PETSITTER    VARCHAR2(100)      NULL,
    PRICE    NUMBER      NULL,
    USER_DATE    DATE      NULL,
    PASSWORD    VARCHAR2(100)      NULL,
    USER_DELETE    VARCHAR2(100)      NULL
);

CREATE TABLE  MESSAGE  (
    SENDER_ID    VARCHAR2(100)      NOT NULL,
    MESSAGE_TITLE    VARCHAR2(100)      NULL,
    MESSAGE_CONTENT    VARCHAR2(2000)      NULL,
    MESSAGE_READ    VARCHAR2(100)      NULL,
    MESSAGE_DATE    DATE      NULL,
    REICEIVER_ID    VARCHAR2(100)      NOT NULL
);

CREATE TABLE  PAYMENT  (
    BOOKING_NO    NUMBER      NOT NULL,
    PAYMENT_DATE    DATE      NOT NULL,
    PAYMENT_METHOD    VARCHAR2(100)      NOT NULL,
    PAYMENT_YN    VARCHAR2(100)      NOT NULL
);

CREATE TABLE  PREBOOKING  (
    PREBOOKING_NO    NUMBER      NOT NULL,
    USER_ID    VARCHAR2(100)      NOT NULL,
    PREBOOKING_TITLE    VARCHAR2(100)      NOT NULL,
    PREBOOKING_CONTENT    VARCHAR2(100)      NOT NULL,
    PREBOOKING_DATE    DATE      NOT NULL,
    ANSWER_YN    VARCHAR2(100)      NOT NULL
);

CREATE TABLE  PREANSWER  (
    PREBOOKING_NO    NUMBER      NOT NULL,
    USER_ID    VARCHAR2(100)      NOT NULL,
    ANSWER_CONTENT    VARCHAR2(4000)      NOT NULL,
    ANSWER_DATE    DATE      NOT NULL
);

CREATE TABLE  QUESTION  (
    INQUIRE_NO    NUMBER      NOT NULL,
    INQUIRE_TITLE    VARCHAR2(100)      NOT NULL,
    INQUIRE_CONTENT    VARCHAR2(4000)      NOT NULL,
    INQUIRE_DATE    DATE      NOT NULL,
    REPLY_YN    VARCHAR2(100)      NOT NULL,
    USER_ID    VARCHAR2(100)      NOT NULL
);

CREATE TABLE  ANSWER  (
    UNQUIRE_NO    NUMBER      NOT NULL,
    REPLY_CONTENT    VARCHAR2(4000)      NOT NULL,
    REPLY_DATE    DATE      NOT NULL
);

CREATE TABLE  TIPBOARD  (
    TIPBOARD_NO    NUMBER      NOT NULL,
    TIPBOARD_TITLE    VARCHAR2(100)      NOT NULL,
    TIPBOARD_CONTENT    VARCHAR2(4000)      NOT NULL,
    TIPBOARD_DATE    DATE      NOT NULL,
    TIPBOARD_ORIGINFILE    VARCHAR2(100)      NULL,
    TIPBOARD_VIEWS    NUMBER      NOT NULL,
    TIPBOARD_RECOMMEND    NUMBER      NOT NULL,
    USER_ID    VARCHAR2(100)      NOT NULL,
    TIPBOARD_DELETE    VARCHAR2(100)      NULL,
    TIPBOARD_REFILE    VARCHAR2(100)      NULL
);

CREATE TABLE  TIPBOARD_REPLY  (
    TIPREPLY_NO    NUMBER      NOT NULL,
    TIPREPLY_CONTENT    VARCHAR2(600)      NOT NULL,
    TIPREPLY_DATE    DATE      NOT NULL,
    TIP_NO    NUMBER      NOT NULL,
    USER_ID    VARCHAR2(100)      NOT NULL,
    TIPREPLY_DELETE    VARCHAR2(100)      NULL
);

CREATE TABLE  FREEBOARD  (
    FREEBOARD_NO    NUMBER      NOT NULL,
    FREEBOARD_TITLE    VARCHAR2(100)      NOT NULL,
    FREEBOARD_CONTENT    VARCHAR2(4000)      NOT NULL,
    FREEBOARD_DATE    DATE      NOT NULL,
    FREEBOARD_ORIGINFILE    VARCHAR2(100)      NULL,
    FREEBOARD_VIEWS    NUMBER      NOT NULL,
    FREEBOARD_RECOMMEND    NUMBER      NOT NULL,
    USER_ID    VARCHAR2(100)      NOT NULL,
    FREEBOARD_DELETE    VARCHAR2(100)      NULL,
    FREEBOARD_REFILE    VARCHAR2(100)      NULL
);

CREATE TABLE  FREEBOARD_REPLY  (
    FREEREPLY_NO    NUMBER      NOT NULL,
    FREEREPLY_CONTENT    VARCHAR2(600)      NOT NULL,
    FREEREPLY_DATE    DATE      NOT NULL,
    USER_ID    VARCHAR2(100)      NOT NULL,
    FREEBOARD_NO    NUMBER      NOT NULL,
    FREEBOARD_DELETE    VARCHAR2(100)      NULL
);

CREATE TABLE  MANAGER  (
    MANAGER_ID    VARCHAR2(100)      NOT NULL,
    MANAGER_NAME    VARCHAR2(100)      NOT NULL,
    MANAGER_RIGHT    VARCHAR2(100)      NOT NULL
);

CREATE TABLE  FAQ  (
    FAQ_NO    NUMBER      NOT NULL,
    FAQ_TITLE    VARCHAR2(100)      NOT NULL,
    FAQ_CONTENT    VARCHAR2(4000)      NOT NULL,
    FAQ_DATE    DATE      NOT NULL,
    FAQ_VIEWS    NUMBER      NOT NULL,
    MANAGER_ID    VARCHAR2(100)      NOT NULL
);

CREATE TABLE  REPORT  (
    REPORT_NO    NUMBER      NOT NULL,
    REPORT_CONTENT    VARCHAR2(4000)      NOT NULL,
    REPORT_CATEGORY    VARCHAR2(100)      NULL,
    BOARD_NO    NUMBER      NULL,
    USER_ID    VARCHAR2(100)      NOT NULL
);

CREATE TABLE  NOTICE  (
    NOTICE_NO    NUMBER      NOT NULL,
    NOTICE_TITLE    VARCHAR2(100)      NOT NULL,
    NOTICE_CONTENT    VARCHAR2(4000)      NOT NULL,
    NOTICE_DATE    DATE      NOT NULL,
    NOTICE_ORIGINFILE    VARCHAR2(100)      NULL,
    NOTICE_VIEWS    NUMBER      NOT NULL,
    MANAGER_ID    VARCHAR2(100)      NOT NULL,
    NOTICE_DELETE    VARCHAR2(100)      NOT NULL,
    NOTICE_REFILE    VARCHAR2(100)      NULL
);

CREATE TABLE  BOOKING  (
    BOOKING_NO    NUMBER      NOT NULL,
    CHECKIN_DATE    DATE      NOT NULL,
    CHECKOUT_DATE    DATE      NOT NULL,
    PET_NO    NUMBER      NOT NULL,
    USER_ID    VARCHAR2(100)      NOT NULL,
    BOOKING_PROGRESS    VARCHAR2(100)      NOT NULL,
    BOOKING_ETC    VARCHAR2(100)      NULL,
    SERVICE_KIND    VARCHAR2(100)      NOT NULL
);

CREATE TABLE  REVIEW  (
    REVIEW_NO    NUMBER      NOT NULL,
    USER_ID    VARCHAR2(100)      NOT NULL,
    BOOKING_NO    NUMBER      NOT NULL,
    POINT    VARCHAR2(100)      NOT NULL,
    REVIEW_CONTENT    VARCHAR2(600)      NOT NULL,
    REVIEW_ORIGINFILE    VARCHAR2(100)      NULL,
    REVIEW_REFILE    VARCHAR2(100)      NULL
);

ALTER TABLE  EDU  ADD CONSTRAINT  PK_EDU  PRIMARY KEY (
    USER_ID 
);

ALTER TABLE  PET  ADD CONSTRAINT  PK_PET  PRIMARY KEY (
    PET_NO 
);

ALTER TABLE  MEMBER  ADD CONSTRAINT  PK_MEMBER  PRIMARY KEY (
    USER_ID 
);

ALTER TABLE  MESSAGE  ADD CONSTRAINT  PK_MESSAGE  PRIMARY KEY (
    SENDER_ID 
);

ALTER TABLE  PAYMENT  ADD CONSTRAINT  PK_PAYMENT  PRIMARY KEY (
    BOOKING_NO 
);

ALTER TABLE  PREBOOKING  ADD CONSTRAINT  PK_PREBOOKING  PRIMARY KEY (
    PREBOOKING_NO 
);

ALTER TABLE  PREANSWER  ADD CONSTRAINT  PK_PREANSWER  PRIMARY KEY (
    PREBOOKING_NO 
);

ALTER TABLE  QUESTION  ADD CONSTRAINT  PK_QUESTION  PRIMARY KEY (
    INQUIRE_NO 
);

ALTER TABLE  ANSWER  ADD CONSTRAINT  PK_ANSWER  PRIMARY KEY (
    UNQUIRE_NO 
);

ALTER TABLE  TIPBOARD  ADD CONSTRAINT  PK_TIPBOARD  PRIMARY KEY (
    TIPBOARD_NO 
);

ALTER TABLE  TIPBOARD_REPLY  ADD CONSTRAINT  PK_TIPBOARD_REPLY  PRIMARY KEY (
    TIPREPLY_NO 
);

ALTER TABLE  FREEBOARD  ADD CONSTRAINT  PK_FREEBOARD  PRIMARY KEY (
    FREEBOARD_NO 
);

ALTER TABLE  FREEBOARD_REPLY  ADD CONSTRAINT  PK_FREEBOARD_REPLY  PRIMARY KEY (
    FREEREPLY_NO 
);

ALTER TABLE  MANAGER  ADD CONSTRAINT  PK_MANAGER  PRIMARY KEY (
    MANAGER_ID 
);

ALTER TABLE  FAQ  ADD CONSTRAINT  PK_FAQ  PRIMARY KEY (
    FAQ_NO 
);

ALTER TABLE  REPORT  ADD CONSTRAINT  PK_REPORT  PRIMARY KEY (
    REPORT_NO 
);

ALTER TABLE  NOTICE  ADD CONSTRAINT  PK_NOTICE  PRIMARY KEY (
    NOTICE_NO 
);

ALTER TABLE  BOOKING  ADD CONSTRAINT  PK_BOOKING  PRIMARY KEY (
    BOOKING_NO 
);

ALTER TABLE  REVIEW  ADD CONSTRAINT  PK_REVIEW  PRIMARY KEY (
    REVIEW_NO 
);

ALTER TABLE  EDU  ADD CONSTRAINT  FK_MEMBER_TO_EDU_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  PET  ADD CONSTRAINT  FK_MEMBER_TO_PET_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  MESSAGE  ADD CONSTRAINT  FK_MEMBER_TO_MESSAGE_1  FOREIGN KEY (
    SENDER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  MESSAGE  ADD CONSTRAINT  FK_MEMBER_TO_MESSAGE_2  FOREIGN KEY (
    REICEIVER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  PAYMENT  ADD CONSTRAINT  FK_BOOKING_TO_PAYMENT_1  FOREIGN KEY (
    BOOKING_NO 
)
REFERENCES  BOOKING  (
    BOOKING_NO 
);

ALTER TABLE  PREBOOKING  ADD CONSTRAINT  FK_MEMBER_TO_PREBOOKING_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  PREANSWER  ADD CONSTRAINT  FK_PREBOOKING_TO_PREANSWER_1  FOREIGN KEY (
    PREBOOKING_NO 
)
REFERENCES  PREBOOKING  (
    PREBOOKING_NO 
);

ALTER TABLE  PREANSWER  ADD CONSTRAINT  FK_MEMBER_TO_PREANSWER_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  QUESTION  ADD CONSTRAINT  FK_MEMBER_TO_QUESTION_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  ANSWER  ADD CONSTRAINT  FK_QUESTION_TO_ANSWER_1  FOREIGN KEY (
    UNQUIRE_NO 
)
REFERENCES  QUESTION  (
    INQUIRE_NO 
);

ALTER TABLE  TIPBOARD  ADD CONSTRAINT  FK_MEMBER_TO_TIPBOARD_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  TIPBOARD_REPLY  ADD CONSTRAINT  FK_TIPBOARD_REPLY_1  FOREIGN KEY (
    TIP_NO 
)
REFERENCES  TIPBOARD  (
    TIPBOARD_NO 
);

ALTER TABLE  TIPBOARD_REPLY  ADD CONSTRAINT  FK_MEMBER_TO_TIPBOARD_REPLY_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  FREEBOARD  ADD CONSTRAINT  FK_MEMBER_TO_FREEBOARD_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  FREEBOARD_REPLY  ADD CONSTRAINT  FK_MEMBER_TO_FREEBOARD_REPLY_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  FREEBOARD_REPLY  ADD CONSTRAINT  FK_FREEBOARD_REPLY_1  FOREIGN KEY (
    FREEBOARD_NO 
)
REFERENCES  FREEBOARD  (
    FREEBOARD_NO 
);

ALTER TABLE  FAQ  ADD CONSTRAINT  FK_MANAGER_TO_FAQ_1  FOREIGN KEY (
    MANAGER_ID 
)
REFERENCES  MANAGER  (
    MANAGER_ID 
);

ALTER TABLE  REPORT  ADD CONSTRAINT  FK_MEMBER_TO_REPORT_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  NOTICE  ADD CONSTRAINT  FK_MANAGER_TO_NOTICE_1  FOREIGN KEY (
    MANAGER_ID 
)
REFERENCES  MANAGER  (
    MANAGER_ID 
);

ALTER TABLE  BOOKING  ADD CONSTRAINT  FK_PET_TO_BOOKING_1  FOREIGN KEY (
    PET_NO 
)
REFERENCES  PET  (
    PET_NO 
);

ALTER TABLE  BOOKING  ADD CONSTRAINT  FK_MEMBER_TO_BOOKING_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  REVIEW  ADD CONSTRAINT  FK_MEMBER_TO_REVIEW_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  REVIEW  ADD CONSTRAINT  FK_BOOKING_TO_REVIEW_1  FOREIGN KEY (
    BOOKING_NO 
)
REFERENCES  BOOKING  (
    BOOKING_NO 
);