DROP TABLE  EDU  CASCADE CONSTRAINTS;
DROP TABLE  PET CASCADE CONSTRAINTS ;
DROP TABLE  MEMBER CASCADE CONSTRAINTS;
DROP TABLE  MESSAGE  CASCADE CONSTRAINTS;
DROP TABLE  PAYMENT  CASCADE CONSTRAINTS;
DROP TABLE  PREBOOKING  CASCADE CONSTRAINTS;
DROP TABLE  PREANSWER CASCADE CONSTRAINTS ;
DROP TABLE  QUESTION  CASCADE CONSTRAINTS;
DROP TABLE  ANSWER  CASCADE CONSTRAINTS;
DROP TABLE  TIPBOARD  CASCADE CONSTRAINTS;
DROP TABLE  TIPBOARD_REPLY  CASCADE CONSTRAINTS;
DROP TABLE  FREEBOARD CASCADE CONSTRAINTS ;
DROP TABLE  FREEBOARD_REPLY  CASCADE CONSTRAINTS;
DROP TABLE  MANAGER CASCADE CONSTRAINTS ;
DROP TABLE  FAQ CASCADE CONSTRAINTS ;
DROP TABLE  REPORT CASCADE CONSTRAINTS ;
DROP TABLE  NOTICE CASCADE CONSTRAINTS ;
DROP TABLE  BOOKING CASCADE CONSTRAINTS ;
DROP TABLE  REVIEW CASCADE CONSTRAINTS ;
DROP TABLE SITTERIMG CASCADE CONSTRAINTS ;

CREATE TABLE  EDU  (
    USER_ID    VARCHAR2(100)      NOT NULL,
    EDU_YN    VARCHAR2(100)      NOT NULL,
    SITTER_YN    VARCHAR2(100)      NOT NULL
);

CREATE TABLE  PET  (
    PET_NO    NUMBER      NOT NULL,
    PET_NAME    VARCHAR2(100)      NOT NULL,
    PET_BREADS    VARCHAR2(100)      NOT NULL,
    PET_DATE    VARCHAR2(100)      NOT NULL,
    PET_SIZE    VARCHAR2(100)      NOT NULL,
    PET_GENDER    VARCHAR2(100)      NOT NULL,
    PET_NEUTRALIZE    VARCHAR2(100)      NOT NULL,
    PET_CHARATER    VARCHAR2(100)      NULL,
    USER_ID    VARCHAR2(100)      NOT NULL,
    PET_ORIGINFILE VARCHAR2(50),
    PET_REFILE VARCHAR2(50)
);
drop sequence seq_petno;
create sequence seq_petno
start with 1
increment by 1
nocycle
nocache;

CREATE TABLE  MEMBER  (
    USER_ID    VARCHAR2(100)      NOT NULL,
    EMAIL    VARCHAR2(100)      NULL,
    USER_NAME    VARCHAR2(100)      NULL,
    ADDRESS    VARCHAR2(100)      NULL,
    PHONE    VARCHAR2(100)      NULL,
    JOB    VARCHAR2(100)      NULL,
    PETSITTER    VARCHAR2(100)   default 'n'   NULL,
    PRICE    NUMBER      NULL,
    USER_DATE    DATE      NULL,
    PASSWORD    VARCHAR2(100)      NULL,
    USER_DELETE    VARCHAR2(100)  default 'n'   NULL,
    USER_ORIGINFILE VARCHAR2(100) NULL,
    USER_REFILE VARCHAR2(100) NULL,
    naver_code VARCHAR2(100) NULL
);

CREATE TABLE SITTERIMG (
	IMG_NO	VARCHAR2(100)		NOT NULL,
	USER_ID	VARCHAR2(100)		NOT NULL,
	IMG_ORIGINFILE	VARCHAR2(100)		NULL,
	IMG_REFILE	VARCHAR2(100)		NULL
);

drop sequence seq_IMGNO;
create sequence seq_IMGNO
start with 1
increment by 1
nocycle
nocache;

CREATE TABLE  MESSAGE  (
    SENDER_ID    VARCHAR2(100)      NOT NULL,
    MESSAGE_TITLE    VARCHAR2(100)      NULL,
    MESSAGE_CONTENT    VARCHAR2(2000)      NULL,
    MESSAGE_READ    VARCHAR2(100)      NULL,
    MESSAGE_DATE    DATE  default sysdate    NULL,
    REICEIVER_ID    VARCHAR2(100)      NOT NULL
);

CREATE TABLE  PAYMENT  (
    BOOKING_NO    NUMBER      NOT NULL,
    PAYMENT_DATE    DATE      NOT NULL,
    PAYMENT_METHOD    VARCHAR2(100)      NOT NULL,
    PAYMENT_YN    VARCHAR2(100)      NOT NULL
);


CREATE TABLE  PREBOOKING  (
    PREBOOKING_NO    NUMBER      NOT NULL,
    USER_ID    VARCHAR2(100)      NOT NULL,
    PREBOOKING_TITLE    VARCHAR2(100)      NOT NULL,
    PREBOOKING_CONTENT    VARCHAR2(100)      NOT NULL,
    PREBOOKING_DATE    DATE   default sysdate   NOT NULL,
    ANSWER_YN    VARCHAR2(100)      NOT NULL
);
drop sequence seq_prebookingno;
create sequence seq_prebookingno
start with 1
increment by 1
nocycle
nocache;

CREATE TABLE  PREANSWER  (
    PREBOOKING_NO    NUMBER      NOT NULL,
    USER_ID    VARCHAR2(100)      NOT NULL,
    ANSWER_CONTENT    VARCHAR2(4000)      NOT NULL,
    ANSWER_DATE    DATE  default sysdate    NOT NULL
);

CREATE TABLE  QUESTION  (
    QUESTION_NO    NUMBER      NOT NULL,
    QUESTION_TITLE    VARCHAR2(100)      NOT NULL,
    QUESTION_CONTENT    VARCHAR2(4000)      NOT NULL,
    QUESTION_DATE    DATE  default sysdate    NOT NULL,
    REPLY_YN    VARCHAR2(100)      NOT NULL,
    USER_ID    VARCHAR2(100)      NOT NULL
);

drop sequence seq_QUESTIONno;
create sequence seq_QUESTIONno
start with 1
increment by 1
nocycle
nocache;

CREATE TABLE  ANSWER  (
    QUESTION_NO    NUMBER      NOT NULL,
    REPLY_CONTENT    VARCHAR2(4000)      NOT NULL,
    REPLY_DATE    DATE   default sysdate   NOT NULL
);

CREATE TABLE  TIPBOARD  (
    TIPBOARD_NO    NUMBER      NOT NULL,
    TIPBOARD_TITLE    VARCHAR2(100)      NOT NULL,
    TIPBOARD_CONTENT    VARCHAR2(4000)      NOT NULL,
    TIPBOARD_DATE    DATE  default sysdate    NOT NULL,
    TIPBOARD_ORIGINFILE    VARCHAR2(100)      NULL,
    TIPBOARD_VIEWS    NUMBER      NOT NULL,
    TIPBOARD_RECOMMEND    NUMBER      NOT NULL,
    USER_ID    VARCHAR2(100)      NOT NULL,
    TIPBOARD_DELETE    VARCHAR2(100)  default 'n'    NULL,
    TIPBOARD_REFILE    VARCHAR2(100)      NULL
);

drop sequence seq_tipboardno;
create sequence seq_tipboardno
start with 1
increment by 1
nocycle
nocache;

CREATE TABLE  TIPBOARD_REPLY  (
    TIPREPLY_NO    NUMBER      NOT NULL,
    TIPREPLY_CONTENT    VARCHAR2(600)      NOT NULL,
    TIPREPLY_DATE    DATE  default sysdate    NOT NULL,
    TIP_NO    NUMBER      NOT NULL,
    USER_ID    VARCHAR2(100)      NOT NULL,
    TIPREPLY_DELETE    VARCHAR2(100)  default 'n'    NULL
);
drop sequence seq_tipreplyno;
create sequence seq_tipreplyno
start with 1
increment by 1
nocycle
nocache;

CREATE TABLE  FREEBOARD  (
    FREEBOARD_NO    NUMBER      NOT NULL,
    FREEBOARD_TITLE    VARCHAR2(100)      NOT NULL,
    FREEBOARD_CONTENT    VARCHAR2(4000)      NOT NULL,
    FREEBOARD_DATE    DATE  default sysdate    NOT NULL,
    FREEBOARD_ORIGINFILE    VARCHAR2(100)      NULL,
    FREEBOARD_VIEWS    NUMBER      NOT NULL,
    FREEBOARD_RECOMMEND    NUMBER      NOT NULL,
    USER_ID    VARCHAR2(100)      NOT NULL,
    FREEBOARD_DELETE    VARCHAR2(100)   default 'n'   NULL,
    FREEBOARD_REFILE    VARCHAR2(100)      NULL
);

drop sequence seq_freeboardno;
create sequence seq_freeboardno
start with 1
increment by 1
nocycle
nocache;

CREATE TABLE  FREEBOARD_REPLY  (
    FREEREPLY_NO    NUMBER      NOT NULL,
    FREEREPLY_CONTENT    VARCHAR2(600)      NOT NULL,
    FREEREPLY_DATE    DATE  default sysdate    NOT NULL,
    USER_ID    VARCHAR2(100)      NOT NULL,
    FREEBOARD_NO    NUMBER      NOT NULL,
    FREEBOARD_DELETE    VARCHAR2(100)  default 'n'    NULL
);

drop sequence seq_freereplyno;
create sequence seq_freereplyno
start with 1
increment by 1
nocycle
nocache;

CREATE TABLE  MANAGER  (
    MANAGER_ID    VARCHAR2(100)      NOT NULL,
    MANAGER_NAME    VARCHAR2(100)      NOT NULL,
    MANAGER_PASSWORD VARCHAR2(100) NOT NULL
);

CREATE TABLE  FAQ  (
    FAQ_NO    NUMBER      NOT NULL,
    FAQ_TITLE    VARCHAR2(100)      NOT NULL,
    FAQ_CONTENT    VARCHAR2(4000)      NOT NULL,
    FAQ_DATE    DATE  default sysdate    NOT NULL,
    MANAGER_ID    VARCHAR2(100)      NOT NULL,
    FAQ_TYPE VARCHAR2(100) NOT NULL
);

drop sequence seq_faqno;
create sequence seq_faqno
start with 1
increment by 1
nocycle
nocache;

drop sequence seq_prebookingno;
create sequence seq_prebookingno
start with 1
increment by 1
nocycle
nocache;

CREATE TABLE  REPORT  (
    REPORT_NO    NUMBER      NOT NULL,
    REPORT_CONTENT    VARCHAR2(4000)      NOT NULL,
    REPORT_CATEGORY    VARCHAR2(100)      NULL,
    BOARD_NO    NUMBER      NULL,
    USER_ID    VARCHAR2(100)      NOT NULL
);

drop sequence seq_reportno;
create sequence seq_reportno
start with 1
increment by 1
nocycle
nocache;

CREATE TABLE  NOTICE  (
    NOTICE_NO    NUMBER      NOT NULL,
    NOTICE_TITLE    VARCHAR2(100)      NOT NULL,
    NOTICE_CONTENT    VARCHAR2(4000)      NOT NULL,
    NOTICE_DATE    DATE   default sysdate   NOT NULL,
    NOTICE_ORIGINFILE    VARCHAR2(100)      NULL,
    NOTICE_VIEWS    NUMBER      NOT NULL,
    MANAGER_ID    VARCHAR2(100)      NOT NULL,
    NOTICE_DELETE    VARCHAR2(100)   default 'n'   NOT NULL,
    NOTICE_REFILE    VARCHAR2(100)      NULL
);

drop sequence seq_noticeno;
create sequence seq_noticeno
start with 1
increment by 1
nocycle
nocache;

CREATE TABLE  BOOKING  (
    BOOKING_NO    NUMBER      NOT NULL,
    CHECKIN_DATE    DATE      NOT NULL,
    CHECKOUT_DATE    DATE      NOT NULL,
    PET_NO    NUMBER      NOT NULL,
    USER_ID    VARCHAR2(100)      NOT NULL,
    BOOKING_PROGRESS    VARCHAR2(100)      NOT NULL,
    BOOKING_ETC    VARCHAR2(100)      NULL,
    SERVICE_KIND    VARCHAR2(100)      NOT NULL,
    PUSER_ID	VARCHAR2(100)	NOT NULL
);

drop sequence seq_bookingno;
create sequence seq_bookingno
start with 1
increment by 1
nocycle
nocache;

CREATE TABLE  REVIEW  (
    REVIEW_NO    NUMBER      NOT NULL,
    USER_ID    VARCHAR2(100)      NOT NULL,
    BOOKING_NO    NUMBER      NOT NULL,
    POINT    VARCHAR2(100)      NOT NULL,
    REVIEW_CONTENT    VARCHAR2(600)      NOT NULL,
    REVIEW_ORIGINFILE    VARCHAR2(100)      NULL,
    REVIEW_REFILE    VARCHAR2(100)      NULL
);

drop sequence seq_reviewno;
create sequence seq_reviewno
start with 1
increment by 1
nocycle
nocache;

ALTER TABLE  EDU  ADD CONSTRAINT  PK_EDU  PRIMARY KEY (
    USER_ID 
);

ALTER TABLE  PET  ADD CONSTRAINT  PK_PET  PRIMARY KEY (
    PET_NO 
);

ALTER TABLE  MEMBER  ADD CONSTRAINT  PK_MEMBER  PRIMARY KEY (
    USER_ID 
);

ALTER TABLE SITTERIMG ADD CONSTRAINT PK_SITTERIMG PRIMARY KEY (
	IMG_NO
);



ALTER TABLE  MESSAGE  ADD CONSTRAINT  PK_MESSAGE  PRIMARY KEY (
    SENDER_ID 
);

ALTER TABLE  PAYMENT  ADD CONSTRAINT  PK_PAYMENT  PRIMARY KEY (
    BOOKING_NO 
);

ALTER TABLE  PREBOOKING  ADD CONSTRAINT  PK_PREBOOKING  PRIMARY KEY (
    PREBOOKING_NO 
);

ALTER TABLE  PREANSWER  ADD CONSTRAINT  PK_PREANSWER  PRIMARY KEY (
    PREBOOKING_NO 
);

ALTER TABLE  QUESTION  ADD CONSTRAINT  PK_QUESTION  PRIMARY KEY (
    QUESTION_NO 
);

ALTER TABLE  ANSWER  ADD CONSTRAINT  PK_ANSWER  PRIMARY KEY (
    QUESTION_NO 
);

ALTER TABLE  TIPBOARD  ADD CONSTRAINT  PK_TIPBOARD  PRIMARY KEY (
    TIPBOARD_NO 
);

ALTER TABLE  TIPBOARD_REPLY  ADD CONSTRAINT  PK_TIPBOARD_REPLY  PRIMARY KEY (
    TIPREPLY_NO 
);

ALTER TABLE  FREEBOARD  ADD CONSTRAINT  PK_FREEBOARD  PRIMARY KEY (
    FREEBOARD_NO 
);

ALTER TABLE  FREEBOARD_REPLY  ADD CONSTRAINT  PK_FREEBOARD_REPLY  PRIMARY KEY (
    FREEREPLY_NO 
);

ALTER TABLE  MANAGER  ADD CONSTRAINT  PK_MANAGER  PRIMARY KEY (
    MANAGER_ID 
);

ALTER TABLE  FAQ  ADD CONSTRAINT  PK_FAQ  PRIMARY KEY (
    FAQ_NO 
);

ALTER TABLE  REPORT  ADD CONSTRAINT  PK_REPORT  PRIMARY KEY (
    REPORT_NO 
);

ALTER TABLE  NOTICE  ADD CONSTRAINT  PK_NOTICE  PRIMARY KEY (
    NOTICE_NO 
);

ALTER TABLE  BOOKING  ADD CONSTRAINT  PK_BOOKING  PRIMARY KEY (
    BOOKING_NO 
);

ALTER TABLE  REVIEW  ADD CONSTRAINT  PK_REVIEW  PRIMARY KEY (
    REVIEW_NO 
);

ALTER TABLE  EDU  ADD CONSTRAINT  FK_MEMBER_TO_EDU_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  PET  ADD CONSTRAINT  FK_MEMBER_TO_PET_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE SITTERIMG ADD CONSTRAINT FK_MEMBER_TO_SITTERIMG_1 FOREIGN KEY (
	USER_ID
)
REFERENCES MEMBER (
	USER_ID
);

ALTER TABLE  MESSAGE  ADD CONSTRAINT  FK_MEMBER_TO_MESSAGE_1  FOREIGN KEY (
    SENDER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  MESSAGE  ADD CONSTRAINT  FK_MEMBER_TO_MESSAGE_2  FOREIGN KEY (
    REICEIVER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  PAYMENT  ADD CONSTRAINT  FK_BOOKING_TO_PAYMENT_1  FOREIGN KEY (
    BOOKING_NO 
)
REFERENCES  BOOKING  (
    BOOKING_NO 
)  ON DELETE CASCADE;

ALTER TABLE  PREBOOKING  ADD CONSTRAINT  FK_MEMBER_TO_PREBOOKING_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  PREANSWER  ADD CONSTRAINT  FK_PREBOOKING_TO_PREANSWER_1  FOREIGN KEY (
    PREBOOKING_NO 
)
REFERENCES  PREBOOKING  (
    PREBOOKING_NO 
);

ALTER TABLE  PREANSWER  ADD CONSTRAINT  FK_MEMBER_TO_PREANSWER_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  QUESTION  ADD CONSTRAINT  FK_MEMBER_TO_QUESTION_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  ANSWER  ADD CONSTRAINT  FK_QUESTION_TO_ANSWER_1  FOREIGN KEY (
    QUESTION_NO 
)
REFERENCES  QUESTION  (
    QUESTION_NO 
);

ALTER TABLE  TIPBOARD  ADD CONSTRAINT  FK_MEMBER_TO_TIPBOARD_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  TIPBOARD_REPLY  ADD CONSTRAINT  FK_TIPBOARD_REPLY_1  FOREIGN KEY (
    TIP_NO 
)
REFERENCES  TIPBOARD  (
    TIPBOARD_NO 
);

ALTER TABLE  TIPBOARD_REPLY  ADD CONSTRAINT  FK_MEMBER_TO_TIPBOARD_REPLY_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  FREEBOARD  ADD CONSTRAINT  FK_MEMBER_TO_FREEBOARD_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  FREEBOARD_REPLY  ADD CONSTRAINT  FK_MEMBER_TO_FREEBOARD_REPLY_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  FREEBOARD_REPLY  ADD CONSTRAINT  FK_FREEBOARD_REPLY_1  FOREIGN KEY (
    FREEBOARD_NO 
)
REFERENCES  FREEBOARD  (
    FREEBOARD_NO 
);

ALTER TABLE  FAQ  ADD CONSTRAINT  FK_MANAGER_TO_FAQ_1  FOREIGN KEY (
    MANAGER_ID 
)
REFERENCES  MANAGER  (
    MANAGER_ID 
);

ALTER TABLE  REPORT  ADD CONSTRAINT  FK_MEMBER_TO_REPORT_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  NOTICE  ADD CONSTRAINT  FK_MANAGER_TO_NOTICE_1  FOREIGN KEY (
    MANAGER_ID 
)
REFERENCES  MANAGER  (
    MANAGER_ID 
);

ALTER TABLE  BOOKING  ADD CONSTRAINT  FK_PET_TO_BOOKING_1  FOREIGN KEY (
    PET_NO 
)
REFERENCES  PET  (
    PET_NO 
) ON DELETE CASCADE;

ALTER TABLE  BOOKING  ADD CONSTRAINT  FK_MEMBER_TO_BOOKING_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
) ON DELETE CASCADE;

ALTER TABLE BOOKING ADD CONSTRAINT FK_MEMBER_TO_BOOKING_2 FOREIGN KEY (
	PUSER_ID
)
REFERENCES MEMBER (
	USER_ID
) on delete cascade;

ALTER TABLE  REVIEW  ADD CONSTRAINT  FK_MEMBER_TO_REVIEW_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  REVIEW  ADD CONSTRAINT  FK_BOOKING_TO_REVIEW_1  FOREIGN KEY (
    BOOKING_NO 
)
REFERENCES  BOOKING  (
    BOOKING_NO 
);


insert into manager values('manager','매니저이름1','pass01');
insert into notice values(seq_noticeno.nextval,'1번글','1번내용',default,'0',0,'manager','n','0');

insert into member values('user01','user1@naver.com','유저1','서울','010-1111-1111','직업1',default,0,'91/06/18','pass01',default,null,null);


insert into tipboard values(seq_tipboardno.nextval,'팁1번글','1번글 내용',default,'0',0,0,'user01',default,'0' );
insert into tipboard values(seq_tipboardno.nextval,'팁2번글','2번글 내용',default,'0',0,0,'user01',default,'0' );



select * from tipboard order by tipboard_no desc;

update tipboard set tipboard_delete = 'y' where tipboard_no = ;

insert into faq values(seq_faqno.nextval, 'faqtest', '내용', sysdate, 'manager', '기타');
commit;