-- DAY11 2019.01.15 -②

-- 데이터 딕셔너리
-- 사용자가 소유한 테이블 객체 정보 : USER_TABLES
SELECT  * FROM USER_TABLES;

-- 사용자가 만든 제약조건 정보 : USER_CONSTRAINTS
SELECT  * FROM USER_CONSTRAINTS;

-- 사용자가 만든 시퀀스 정보 : USER_SEQUENCES
SELECT  * FROM USER_SEQUENCES;

-- 사용자가 만든 인덱스 정보 : USER_INDEXES
SELECT  * FROM USER_INDEXES;

-- 사용자가 만든 뷰 정보 : USER_VIEWS
SELECT  * FROM USER_VIEWS;

-- 사용자가 만든 테이블, 뷰, 시퀀스 정보 : USER_CATALOG
SELECT  * FROM USER_CATALOG;

-- 현재 사용자가 접근할 수 있는 모든 테이블 정보 : ALL_TABLES;
SELECT  * FROM ALL_TABLES;

-- DBA(데이터베이스관리자)가 접근할 수 있는 테이블 조회 : DBA_TABLES
SELECT  * FROM DBA_TABLES; -- SYSTEM계정으로 접근 가능함.

-- 사용자가 만든 모든 객체 정보 : USER_OBJECTS
SELECT  * FROM USER_OBJECTS;
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- DDL
-- CREATE, ALTER, DROP
-- TABLE : CREATE TABLE, ALTER TABLE, DROP TABLE
-- VIEW : CREATE VIEW, DROP VIEW
-- SEQUENCE : CREATE SEQUENCE, ALTER SEQUENCE, DROP SEQUENCE

-- 테이블 수정
-- COLUMN 추가/삭제, 제약조건 추가/삭제
-- COLUMN 자료형 변경, DEFAULT값 변경
-- 테이블명, 컬럼명, 제약조건이름 변경

-- 컬럼 추가
-- 테이블 작성시 COLUMN설정과 동일하게 작성하면 된다.
ALTER TABLE DCOPY
ADD (LNAME      VARCHAR2(40));

DESC DCOPY;

ALTER TABLE DCOPY
ADD (CNAME      VARCHAR2(30) DEFAULT '한국');

SELECT  * FROM DCOPY;

-- 제약조건 추가
CREATE TABLE EMP2
AS  SELECT  *
    FROM    EMPLOYEE;
    
ALTER TABLE EMP2
ADD PRIMARY KEY (EMP_ID);

ALTER TABLE EMP2
ADD CONSTRAINT E2_UNENO UNIQUE (EMP_NO);

-- 단, NOT NULL은 ADD할 수 없다. 
-- COLUMN에 NULL가능 -> NULL 불가능.. 의 변경개념. 따라서 MODIFY를 사용해야한다.
/*ALTER TABLE EMP2
ADD NOT NULL (HIRE_DATE);*/ -- ERROR
ALTER TABLE EMP2
MODIFY  (HIRE_DATE NOT NULL);

-- COLUMN 자료형 변경
CREATE TABLE EMP4
AS  SELECT  EMP_ID, EMP_NAME, HIRE_DATE
    FROM    EMPLOYEE;

SELECT  * FROM EMP4;
DESC EMP4;

ALTER TABLE EMP4
MODIFY  (EMP_ID VARCHAR2(5),
         EMP_NAME CHAR(20));
         
-- 값이 기록된 COLUMN은 다른 자료형으로 바꿀 수 없음
/*ALTER TABLE EMP4
MODIFY (HIRE_DATE CHAR(8));*/ -- ERROR

-- 문자열 자료형은 크기를 줄이는 변경을 할 수 없다.
/*ALTER TABLE EMP4
MODIFY (EMP_NAME CHAR(15));*/ -- ERROR

-- DEFAULT 값 변경
CREATE TABLE EMP5
(
 EMP_ID     CHAR(3),
 EMP_NAME   VARCHAR2(20),
 ADDR1      VARCHAR2(20) DEFAULT '서울',
 ADDR2      VARCHAR2(100)
);
INSERT INTO EMP5 VALUES ('R11','임태희',DEFAULT,'청담동');
INSERT INTO EMP5 VALUES ('P10','이병언',DEFAULT,'양재동');
SELECT  * FROM EMP5;
DESC EMP5;

ALTER TABLE EMP5
MODIFY  (ADDR1  DEFAULT '경기');
--DEFAULT 변경이후의 값만 적용됨
INSERT INTO EMP5 VALUES ('E31','임승우',DEFAULT,'분당 효자동');

-- COLUMN 삭제
ALTER TABLE DCOPY
DROP COLUMN CNAME;

DESC DCOPY;
SELECT  * FROM DCOPY;

ALTER TABLE DCOPY
DROP (LNAME);

-- COLUMN 여러 개 삭제
ALTER TABLE DCOPY
DROP (DNAME, LID);

-- DROP (DI); -- 마지막 남은 COLUMN이라 삭제 불가. ERROR
-- 테이블은 최소 한 개의 COLUMN을 가지고 있어야 한다.
/*ALTER TABLE DCOPY
DROP COLUMN DID;*/ -- ERROR
-- 지금까지 DCOPY에서 DROP으로 삭제한 COULUMN들은 복구할 수 없다.

-- 제약조건이 있는 COLUMN은 삭제할 수 없는 것이 원칙.
/*ALTER TABLE DEPARTMENT
DROP (DEPT_ID);*/ -- PRIMARY, REFERENCES 참조중이므로 삭제불가. ERROR
CREATE TABLE TB1
(
 PK     NUMBER PRIMARY KEY,
 FK     NUMBER REFERENCES TB1,
 COL1   NUMBER,
 CHECK  (PK > 0 AND COL1 > 0)
);
/*ALTER TABLE TB1
DROP (PK);*/ -- ERRO. PRIMARY KEY 되어있음.
-- 만약 제약조건 COLUMN을 삭제하고 싶다면 제약조건도 같이 삭제하면 된다.
-- CASCADE
ALTER TABLE TB1
DROP (PK)   CASCADE CONSTRAINTS;
-- 이건 삭제 됨.
DESC CONSTRAINT_EMP;

ALTER TABLE TB1
DROP (COL1) CASCADE CONSTRAINTS;

-- 제약조건 삭제
-- 1개 삭제
ALTER TABLE CONSTRAINT_EMP
DROP CONSTRAINT CHK;

-- 여러 개 삭제일 때
ALTER TABLE CONSTRAINT_EMP
DROP CONSTRAINT FKJID
DROP CONSTRAINT FKMID
DROP CONSTRAINT FKDID;

-- 데이터 딕셔너리를 통해 삭제 확인
SELECT  TABLE_NAME, CONSTRAINT_NAME
FROM    USER_CONSTRAINTS
WHERE   TABLE_NAME = 'CONSTRAINT_EMP';

-- NOT NULL제약조건은 삭제가 아니라 NULL로 변경함
-- DROP이 아니라 MODIFY사용함
ALTER TABLE CONSTRAINT_EMP
MODIFY (ENAME NULL, ENO NULL);

-- 테이블의 컬럼을 관리하는 데이터 딕셔너리 : USER_TAB_COLS
SELECT  * FROM USER_TAB_COLS;
DESC USER_TAB_COLS;

SELECT  TABLE_NAME, COLUMN_NAME, NULLABLE
FROM    USER_TAB_COLS
WHERE   TABLE_NAME = 'CONSTRAINT_EMP';

-- 테이블의 컬럼별 제약조건을 관리하는 딕셔너리 : USER_CONS_COLUMNS
CREATE TABLE TB_EXAM
(
 COL1       CHAR(3) PRIMARY KEY,
 ENAME      VARCHAR(2),
 FOREIGN KEY (COL1) REFERENCES EMPLOYEE
);
SELECT  CONSTRAINT_NAME AS 조건이름,
        CONSTRAINT_TYPE AS 유형,
        COLUMN_NAME AS 컬럼,
        R_CONSTRAINT_NAME AS 참조,
        DELETE_RULE AS 삭제규칙
FROM    USER_CONSTRAINTS
JOIN    USER_CONS_COLUMNS USING (CONSTRAINT_NAME, TABLE_NAME)
WHERE   TABLE_NAME = 'TB_EXAM';

-- 이름바꾸기
-- COLUMN, CONSTRAINTS, TABLE 이름 변경가능

-- Ⅰ. COLUMN이름 바꾸기
ALTER TABLE TB_EXAM
RENAME COLUMN COL1 TO EMPID;

DESC TB_EXAM;

-- Ⅱ. CONSTRAINTS이름 바꾸기
ALTER TABLE TB_EXAM
RENAME CONSTRAINTS SYS_C007268 TO PK_EID;

ALTER TABLE TB_EXAM
RENAME CONSTRAINTS SYS_C007269 TO FK_EID;

-- Ⅲ. TABLE이름 바꾸기
ALTER TABLE TB_EXAM RENAME TO TB_SAMPLE1;
--OR
RENAME TB_SAMPLE1 TO TB_SAMPLE;

-- DELETE TABLE : 테이블 삭제
-- DROP TABLE 테이블이름;
-- FOREIGN KEY 제약조건으로 참조되고 있는 테이블은 삭제할 수 없다.
CREATE TABLE DEPT2
(
 DID        CHAR(2) PRIMARY KEY,
 DNAME      VARCHAR(10)
);

CREATE TABLE EMP6
(
 EID        CHAR(3) PRIMARY KEY,
 ENAME      VARCHAR(10),
 DID        CHAR(2) REFERENCES DEPT2
);

-- DROP TABLE DEPT2; -- ERROR. EMP6이 DEPT를 참조중이기에 삭제할 수 없다.
-- 따라서 DEPT2를 삭제하고 싶다면 DEPT2의 REFERENCES 제약조건을 함께 삭제해야한다.
DROP TABLE DEPT2 CASCADE CONSTRAINTS;
-- 데이터 딕셔너리를 통해 위의 작업 확인
SELECT  TABLE_NAME
FROM    USER_TABLES
WHERE   TABLE_NAME LIKE 'D%';