/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-03-25 10:06:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.findSitter;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URLEncoder;
import java.security.SecureRandom;
import java.math.BigInteger;
import member.model.vo.Member;

public final class petSitterListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/findSitter/..//common/footer.jsp", Long.valueOf(1553173318000L));
    _jspx_dependants.put("/views/findSitter/..//common/menu.jsp", Long.valueOf(1553508275457L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.security.SecureRandom");
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("java.math.BigInteger");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Dog House</title>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"/doggybeta/resources/images/favicon.ico\">\r\n");
      out.write("<link href=\"/doggybeta/resources/css/footer.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/doggybeta/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body{\r\n");
      out.write("\twidth: 1500px;\r\n");
      out.write("\t margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("}\r\n");
      out.write(".checked {\r\n");
      out.write("  color: orange;\r\n");
      out.write("}\r\n");
      out.write("#searchpettable{\r\n");
      out.write("\tbackground-color: #f3f6f7;\r\n");
      out.write("\tpadding: 30px 30px;\r\n");
      out.write("\tmargin: 10px 10px;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\twidth: 800px;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("}\r\n");
      out.write("input[type=button]{\r\n");
      out.write("\tbackground-color: #2ec4b6;\r\n");
      out.write("\twidth:100px; height:30px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tborder-radius: 12px;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write(" \ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table td{\r\n");
      out.write("text-align: center;\r\n");
      out.write("}\r\n");
      out.write(" #detail table{\r\n");
      out.write("\tmargin: 8px;\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("#detailtable:hover{\r\n");
      out.write("\tbackground-color: rgba(210, 222, 225, 0.5);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member loginUser = (Member)session.getAttribute("loginUser");
	String access_token = (String)session.getAttribute("access_token");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/doggybeta/resources/css/psForm.css\">\r\n");
      out.write("<link href='/doggybeta/resources/css/login.css' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Sunflower:300,500,700&amp;subset=korean\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/doggybeta/resources/css/mainV2.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/doggybeta/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://static.nid.naver.com/js/naveridlogin_js_sdk_2.0.0.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t $(function() {\r\n");
      out.write(" \t\t$('.login-form').hide();\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t$('.btn').click(function() {\r\n");
      out.write("\t\t\t$('body').append('<div id=\"mask\"></div>');\r\n");
      out.write("\t\t    $('#mask').fadeIn(300);\r\n");
      out.write("\t\t    $('.login-form').fadeIn(300);\r\n");
      out.write("\t\t\t$('.login-form').show();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t    $('#mask').click(function() {\r\n");
      out.write("\t\t    \t$('#mask, .login-form').fadeOut(300);\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t $(function() {\r\n");
      out.write("\t\tif(access_token != null) {\r\n");
      out.write("\t\t\t$('.userid').val(loginUser.getUserId());\r\n");
      out.write("\t\t\t$('.passwd').val(loginUser.getUserpwd());\r\n");
      out.write("\t\t\tform.submit();\r\n");
      out.write("\t\t} \r\n");
      out.write("\t });\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
 if(loginUser == null || access_token == null) { 
      out.write("\r\n");
      out.write("\t<input type='checkbox' id='menu_state' checked />\r\n");
      out.write("\t<div id='mask'> </div>\r\n");
      out.write("\t<nav>\r\n");
      out.write("\t\t<ul class='doghouse'>\r\n");
      out.write("\t\t\t<li><a><span>doghouse</span></a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<span class='btn btn-1 btn-sign'>회원가입/로그인</span>\r\n");
      out.write("\t\t<!-- ---------------------------------------------------------------------------- -->\r\n");
      out.write("\t\t<!-- MENU -->\r\n");
      out.write("\t\t<ul class='icon' id='icon'>\r\n");
      out.write("\t\t\t<li><a href='/doggybeta' id='icon1'> <span>&nbsp;&nbsp;&nbsp;홈</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t\t<li class=\"m1\"><a\r\n");
      out.write("\t\t\t\thref=\"#\" id='icon2'><span>&nbsp;&nbsp;&nbsp;About\r\n");
      out.write("\t\t\t\t\t\tus</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"m2\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/doggybeta/views/aboutus/companyIntroduce.jsp\">회사소개</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a>연혁</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/doggybeta/views/aboutus/teamIntroduce.jsp\">팀\r\n");
      out.write("\t\t\t\t\t\t\t도그집사</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/doggybeta/views/aboutus/location.jsp\">오시는 길</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li><a href='/doggybeta/views/findSitter/petSitterListView.jsp' id='icon3'> <span>&nbsp;&nbsp;&nbsp;펫시터\t찾기</span></a> </li>\r\n");
      out.write("\t\t\t<li class=\"m1\"><a href='#'  id='icon4'> <span>&nbsp;&nbsp;&nbsp;게시판</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<ul class=\"m2\">\r\n");
      out.write("\t\t\t\t\t<li><a href='/doggybeta/nlist'>공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='/doggybeta/flist'>자유게시판</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='/doggybeta/tlist'>팁</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"m1\"><a href=\"#\" id='icon5'> <span>&nbsp;&nbsp;&nbsp;고객센터</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"m2\">\r\n");
      out.write("\t\t\t\t\t<li><a href='/doggybeta/faqlist'>FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>이용방법</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>1:1문의</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"m1\"><a href=\"#\" id='icon6'><span>&nbsp;&nbsp;&nbsp;마이페이지</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"m2\">\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>정보수정</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>이용내역/예약확인</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='#' id=\"pet_reg__btn\">펫시터신청</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>사전문의확인</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<!-- Login Form ---------------------------------------------------------------------------- -->\r\n");
      out.write("\t<form class=\"login-form\" method='post' action='/doggybeta/jipsalogin'>\r\n");
      out.write("    <!-- <img id='cancelBtn' src='/doggybeta/resources/images/cancel-button.jpg'> -->\r\n");
      out.write("  \t\t\t<p class=\"login-text\">\r\n");
      out.write("  \t\t\t\tDOGHOUSE\r\n");
      out.write("  \t\t\t</p> \r\n");
      out.write("  \t\t\t<input type=\"text\" name='userid' id='userid' class=\"login-username\" autofocus required placeholder=\"Email\" />\r\n");
      out.write("  \t\t\t<input type=\"password\" name='userpwd' id='passwd' class=\"login-password\" required required placeholder=\"Password\" />\r\n");
      out.write("  \t\t\t<a href='/doggybeta/jipsalogin'>\r\n");
      out.write("  \t\t\t<input type=\"submit\" name=\"Login\" value=\"Login\" class=\"login-submit\" id='btnLogin'/></a><br>\r\n");
      out.write("\t\t\t<a href='/doggybeta/views/member/termsOfService.jsp'>\r\n");
      out.write("\t\t\t<input type=\"button\" name='enroll' value='회원가입' class='login-submit' id='btnEnroll'/></a>\r\n");
      out.write("\t\t\t<p align='center' id='orid'>------- 또는 -------</p>\r\n");
      out.write("\t\t\t<!-- http://127.0.0.1:8888/doggybeta/views/member/callback.jsp -->\r\n");
      out.write("\t\t\t");

   				 String clientId = "obXTFPuiHDCuNQb5kAmx";//애플리케이션 클라이언트 아이디값";
   				 String redirectURI = URLEncoder.encode("http://127.0.0.1:8888/doggybeta/naverlogin", "UTF-8");
   				 SecureRandom random = new SecureRandom();
   				 String state = new BigInteger(130, random).toString();
   				 String apiURL = "https://nid.naver.com/oauth2.0/authorize?response_type=code";
   				 apiURL += "&client_id=" + clientId;
   				 apiURL += "&redirect_uri=" + redirectURI;
   				 apiURL += "&state=" + state;
   				 session.setAttribute("state", state);
    		 
      out.write("\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(apiURL);
      out.write("\"><img style='position:relative;' height=\"47\" width='240' src=\"/doggybeta/resources/images/naverButton/네이버 아이디로 로그인_완성형_White.PNG\"/></a> \r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("  \t\t\t<a href=\"/doggybeta/views/member/findPassword.jsp\" class=\"login-forgot-pass\" id='tempPwd'>비밀번호를 잊으셨나요?</a>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t$('.m1').click(function() {\r\n");
      out.write("\t\tif ($(this).children('.m2').is(':visible')) {\r\n");
      out.write("\t\t\t$(this).children('.m2').slideUp(200);\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$(this).children('.m2').slideDown(200);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t");
 } else { 
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t");
      out.print( loginUser.getUserId() );
      out.write(" 님 환영합니다\r\n");
      out.write("\t\t<a href='/doggybeta/jipsalogout'>로그아웃</a>\r\n");
      out.write("\t\t<input type='checkbox' id='menu_state' checked />\r\n");
      out.write("\t<nav>\r\n");
      out.write("\t\t<ul class='doghouse'>\r\n");
      out.write("\t\t\t<li><a><span>doghouse</span></a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<a  href='/doggybeta/jipsalogout'><span class='btn btn-1 btn-sign'>로그아웃</span></a>\r\n");
      out.write("\t\t");
      out.print( loginUser.getUserId() );
      out.write("\r\n");
      out.write("\t\t");
      out.print( access_token );
      out.write("님 환영해요!\r\n");
      out.write("\t\t<!-- ---------------------------------------------------------------------------- -->\r\n");
      out.write("<!-- \t\t<a href=\"#\" class=\"login-forgot-pass\">forgot password?</a>\r\n");
      out.write("\t\t<div class=\"underlay-photo\"></div>\r\n");
      out.write("\t\t<div class=\"underlay-black\"></div>  -->\r\n");
      out.write("\t\t<!-- -------------------------------------------------------------------------  -->\r\n");
      out.write("\t\t<ul class='icon' id='icon'>\r\n");
      out.write("\t\t\t<li><a href='/doggybeta' id='icon1'> <span>&nbsp;&nbsp;&nbsp;홈</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t\t<li class=\"m1\"><a\r\n");
      out.write("\t\t\t\thref=\"/doggybeta/views/aboutus/companyintroduce.jsp\" id='icon2'><span>&nbsp;&nbsp;&nbsp;About\r\n");
      out.write("\t\t\t\t\t\tus</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"m2\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/doggybeta/views/aboutus/companyIntroduce.jsp\">회사소개</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a>연혁</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/doggybeta/views/aboutus/teamIntroduce.jsp\">팀\r\n");
      out.write("\t\t\t\t\t\t\t도그집사</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/doggybeta/views/aboutus/location.jsp\">오시는 길</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li><a href='#' id='icon3'> <span>&nbsp;&nbsp;&nbsp;펫시터\t찾기</span></a> </li>\r\n");
      out.write("\t\t\t<li class=\"m1\"><a href='#'  id='icon4'> <span>&nbsp;&nbsp;&nbsp;게시판</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<ul class=\"m2\">\r\n");
      out.write("\t\t\t\t\t<li><a href='/doggybeta/nlist'>공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='/doggybeta/flist'>자유게시판</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='/doggybeta/tlist'>팁</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"m1\"><a href=\"#\" id='icon5'> <span>&nbsp;&nbsp;&nbsp;고객센터</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"m2\">\r\n");
      out.write("\t\t\t\t\t<li><a href='/doggybeta/faqlist'>FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>이용방법</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>1:1문의</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"m1\"><a href=\"#\" id='icon6'><span>&nbsp;&nbsp;&nbsp;마이페이지</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"m2\">\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>정보수정</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='/doggybeta/views/customerservice/checkMyLog.jsp'>이용내역/예약확인</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='#' id=\"pet_reg__btn\">펫시터신청</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>사전문의확인</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 펫시터 신청 버튼 클릭시 생성 보여지는 HTML 부분. 로그인 부분 구현시 인풋에 세션으로 값 넣어놓고 readonly 처리할 것  -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<form class=\"ps_reg_form\" action=\"/doggybeta/hostup\" method=\"POST\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t<span class=\"close\">x</span>\r\n");
      out.write("\t\t\t\t<div class=\"section1\">\r\n");
      out.write("\t\t\t\t\t<p>아이디</p>\r\n");
      out.write("\t\t\t\t\t<input name=\"userid\" value=\"");
      out.print(loginUser.getUserId() );
      out.write("\"  class=\"ps_input input_id\" autocomplete=\"off\" readonly>\r\n");
      out.write("\t\t\t\t\t<p>이름</p>\r\n");
      out.write("\t\t\t\t\t<input name=\"username\" value=\"");
      out.print(loginUser.getUserName() );
      out.write("\"  class=\"ps_input input_name\" autocomplete=\"off\" >\r\n");
      out.write("\t\t\t\t\t<p>회원 약관</p>\r\n");
      out.write("\t\t\t\t\t<button class=\"normal_btn\">내용보기</button>\r\n");
      out.write("\t\t\t\t\t<p>개인 정보 수집</p>\r\n");
      out.write("\t\t\t\t\t<button class=\"normal_btn\">내용보기</button>\r\n");
      out.write("\t\t\t\t\t<p>제 3자 개인 정보 제공</p>\r\n");
      out.write("\t\t\t\t\t<button class=\"normal_btn\">내용보기</button>\r\n");
      out.write("\t\t\t\t\t<p>전체 동의 여부</p>\r\n");
      out.write("\t\t\t\t\t<span><label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"agree\" value=\"agree\" checked> 동의\r\n");
      out.write("\t\t\t\t\t</label><label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"agree\" value=\"disagree\"> 동의하지않음\r\n");
      out.write("\t\t\t\t\t</label></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"section2\">\r\n");
      out.write("\t\t\t\t\t<p>연락처</p>\r\n");
      out.write("\t\t\t\t\t<input name=\"phone\" value=\"");
      out.print(loginUser.getPhone() );
      out.write("\" class=\"ps_input input_phone\" autocomplete=\"off\" >\r\n");
      out.write("\t\t\t\t\t<p>이메일</p>\r\n");
      out.write("\t\t\t\t\t<input name=\"email\" value=\"");
      out.print(loginUser.getEmail() );
      out.write("\" class=\"ps_input input_email\" autocomplete=\"off\" >\r\n");
      out.write("\t\t\t\t\t<p>펫시팅 장소</p>\r\n");
      out.write("\t\t\t\t\t<input name=\"addr\" placeholder=\"장소/위치 입력\" class=\"ps_input input_addr\" autocomplete=\"off\" >\r\n");
      out.write("\t\t\t\t\t<p>희망 일급(원)</p>\r\n");
      out.write("\t\t\t\t\t<input type=\"number\" name=\"price\" placeholder=\"가격 입력\" class=\"ps_input input_price\" min=\"100\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"section3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"image_box\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"image_box_pic\" />\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"file\" id=\"real-file\" name=\"pic\" hidden=\"hidden\" />\r\n");
      out.write("\t\t\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" id=\"fake-file-btn\" class=\"normal_btn\">Choose a File</button>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"file-text\"></span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"map_box\"></div>\r\n");
      out.write("\t\t\t\t\t<span><button id=\"submit-btn\">펫시터 등록하기</button></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"ps_reg_form_popup_box\">\r\n");
      out.write("\t\t\t\t\t<p>펫시터 등록 신청이 완료되었습니다. </p>\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\">확인</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\"src=\"/doggybeta/resources/js/petSitting.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t$('.m1').click(function() {\r\n");
      out.write("\t\tif ($(this).children('.m2').is(':visible')) {\r\n");
      out.write("\t\t\t$(this).children('.m2').slideUp(200);\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$(this).children('.m2').slideDown(200);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<div id=\"wrap\" >\r\n");
      out.write("<div id=\"content\">\r\n");
      out.write("\t\t\t<!-- 조건 검색 테이블  -->\t\r\n");
      out.write("\t\t\t<div align=center>\t\t\r\n");
      out.write("\t\t\t<table id=searchpettable>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th width=\"100\">서비스</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"300\">날짜</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"100\">견종</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"100\">반려견크기</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"100\">반려견나이</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>  \r\n");
      out.write("\t\t\t\t\t\t<select style=\"width:100px; height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t  <option value=\"volvo\">펫 맡기기</option>\r\n");
      out.write("\t\t\t\t\t\t  <option value=\"saab\">펫시터 방문</option>\r\n");
      out.write("\t\t\t\t\t\t  <option value=\"opel\">반나절 서비스</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"date\" name=\"begin\" style=\"width:120px; height:30px;\"> ~ \r\n");
      out.write("\t\t\t\t\t<input type=\"date\" name=\"end\" style=\"width:120px; height:30px;\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t견종정보\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t사이즈정보\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t나이정보\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</div> <br>\r\n");
      out.write("<!-- 지역 검색 -->\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write(" <form name=\"form1\">\r\n");
      out.write("  <select name=\"h_area1\" onChange=\"cat1_change(this.value,h_area2)\" style=\"width:80px; height:30px;\">\r\n");
      out.write("   <option selected>-선택-</option>\r\n");
      out.write("<option value='1'>서울</option>\r\n");
      out.write("<option value='2'>부산</option>\r\n");
      out.write("<option value='3'>대구</option>\r\n");
      out.write("<option value='4'>인천</option>\r\n");
      out.write("<option value='5'>광주</option>\r\n");
      out.write("<option value='6'>대전</option>\r\n");
      out.write("<option value='7'>울산</option>\r\n");
      out.write("<option value='8'>강원</option>\r\n");
      out.write("<option value='9'>경기</option>\r\n");
      out.write("<option value='10'>경남</option>\r\n");
      out.write("<option value='11'>경북</option>\r\n");
      out.write("<option value='12'>전남</option>\r\n");
      out.write("<option value='13'>전북</option>\r\n");
      out.write("<option value='14'>제주</option>\r\n");
      out.write("<option value='15'>충남</option>\r\n");
      out.write("<option value='16'>충북</option>\r\n");
      out.write("  </select>\r\n");
      out.write("  <select name=\"h_area2\" style=\"width:80px; height:30px;\">\r\n");
      out.write("   <option selected>-선택-</option>\r\n");
      out.write("<option value='215'>군산시</option>\r\n");
      out.write("<option value='216'>김제시</option>\r\n");
      out.write("<option value='217'>남원시</option>\r\n");
      out.write("<option value='218'>익산시</option>\r\n");
      out.write("<option value='219'>전주시 덕진구</option>\r\n");
      out.write("<option value='220'>전주시 완산구</option>\r\n");
      out.write("<option value='221'>정읍시</option>\r\n");
      out.write("<option value='222'>고창군</option>         \r\n");
      out.write("<option value='223'>무주군</option>\r\n");
      out.write("<option value='224'>부안군</option>\r\n");
      out.write("<option value='225'>순창군</option>\r\n");
      out.write("<option value='226'>완주군</option>\r\n");
      out.write("<option value='227'>임실군</option>\r\n");
      out.write("<option value='228'>장수군</option>\r\n");
      out.write("<option value='229'>진안군</option>\r\n");
      out.write("</select>\r\n");
      out.write("<script language=javascript>\r\n");
      out.write("\r\n");
      out.write(" var cat1_num = new Array(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16);\r\n");
      out.write(" var cat1_name = new Array('서울','부산','대구','인천','광주','대전','울산','강원','경기','경남','경북','전남','전북','제주','충남','충북');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" var cat2_num = new Array();\r\n");
      out.write(" var cat2_name = new Array();\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" cat2_num[1] = new Array(17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41);\r\n");
      out.write(" cat2_name[1] = new Array('강남구','강동구','강북구','강서구','관악구','광진구','구로구','금천구','노원구','도봉구','동대문구','동작구','마포구','서대문구','서초구','성동구','성북구','송파구','양천구','영등포구','용산구','은평구','종로구','중구','중랑구');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" cat2_num[2] = new Array(42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57);\r\n");
      out.write(" cat2_name[2] = new Array('강서구','금정구','남구','동구','동래구','부산진구','북구','사상구','사하구','서구','수영구','연제구','영도구','중구','해운대구','기장군');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" cat2_num[3] = new Array(58,59,60,61,62,63,64,65);\r\n");
      out.write(" cat2_name[3] = new Array('남구','달서구','동구','북구','서구','수성구','중구','달성군');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" cat2_num[4] = new Array(66,67,68,69,70,71,72,73,74,75);\r\n");
      out.write(" cat2_name[4] = new Array('계양구','남구','남동구','동구','부평구','서구','연수구','중구','강화군','옹진군');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" cat2_num[5] = new Array(76,77,78,79,80);\r\n");
      out.write(" cat2_name[5] = new Array('광산구','남구','동구','북구','서구');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" cat2_num[6] = new Array(81,82,83,84,85);\r\n");
      out.write(" cat2_name[6] = new Array('대덕구','동구','서구','유성구','중구');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" cat2_num[7] = new Array(86,87,88,89,90);\r\n");
      out.write(" cat2_name[7] = new Array('남구','동구','북구','중구','울주군');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" cat2_num[8] = new Array(91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108);\r\n");
      out.write(" cat2_name[8] = new Array('강릉시','동해시','삼척시','속초시','원주시','춘천시','태백시','고성군','양구군','양양군','영월군','인제군','정선군','철원군','평창군','홍천군','화천군','횡성군');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" cat2_num[9] = new Array(109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148);\r\n");
      out.write(" cat2_name[9] = new Array('고양시 덕양구','고양시 일산구','과천시','광명시','광주시','구리시','군포시','김포시','남양주시','동두천시','부천시 소사구','부천시 오정구','부천시 원미구','성남시 분당구','성남시 수정구','성남시 중원구','수원시 권선구','수원시 장안구','수원시 팔달구','시흥시','안산시 단원구','안산시 상록구','안성시','안양시 동안구','안양시 만안구','오산시','용인시','의왕시','의정부시','이천시','파주시','평택시','하남시','화성시','가평군','양주군','양평군','여주군','연천군','포천군');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" cat2_num[10] = new Array(149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168);\r\n");
      out.write(" cat2_name[10] = new Array('거제시','김해시','마산시','밀양시','사천시','양산시','진주시','진해시','창원시','통영시','거창군','고성군','남해군','산청군','의령군','창녕군','하동군','함안군','함양군','합천군');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" cat2_num[11] = new Array(169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192);\r\n");
      out.write(" cat2_name[11] = new Array('경산시','경주시','구미시','김천시','문경시','상주시','안동시','영주시','영천시','포항시 남구','포항시 북구','고령군','군위군','봉화군','성주군','영덕군','영양군','예천군','울릉군','울진군','의성군','청도군','청송군','칠곡군');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" cat2_num[12] = new Array(193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214);\r\n");
      out.write(" cat2_name[12] = new Array('광양시','나주시','목포시','순천시','여수시','강진군','고흥군','곡성군','구례군','담양군','무안군','보성군','신안군','영광군','영암군','완도군','장성군','장흥군','진도군','함평군','해남군','화순군');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" cat2_num[13] = new Array(215,216,217,218,219,220,221,222,223,224,225,226,227,228,229);\r\n");
      out.write(" cat2_name[13] = new Array('군산시','김제시','남원시','익산시','전주시 덕진구','전주시 완산구','정읍시','고창군','무주군','부안군','순창군','완주군','임실군','장수군','진안군');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" cat2_num[14] = new Array(230,231,232,233);\r\n");
      out.write(" cat2_name[14] = new Array('서귀포시','제주시','남제주군','북제주군');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" cat2_num[15] = new Array(234,235,236,237,238,239,240,241,242,243,244,245,246,247,248);\r\n");
      out.write(" cat2_name[15] = new Array('공주시','논산시','보령시','서산시','아산시','천안시','금산군','당진군','부여군','서천군','연기군','예산군','청양군','태안군','홍성군');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" cat2_num[16] = new Array(249,250,251,252,253,254,255,256,257,258,259,260);\r\n");
      out.write(" cat2_name[16] = new Array('제천시','청주시 상당구','청주시 흥덕구','충주시','괴산군','단양군','보은군','영동군','옥천군','음성군','진천군','청원군');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function cat1_change(key,sel){\r\n");
      out.write(" if(key == '') return;\r\n");
      out.write(" var name = cat2_name[key];\r\n");
      out.write(" var val = cat2_num[key];\r\n");
      out.write("\r\n");
      out.write(" for(i=sel.length-1; i>=0; i--)\r\n");
      out.write("  sel.options[i] = null;\r\n");
      out.write(" sel.options[0] = new Option('-선택-','', '', 'true');\r\n");
      out.write(" for(i=0; i<name.length; i++){\r\n");
      out.write("  sel.options[i+1] = new Option(name[i],val[i]);\r\n");
      out.write(" }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function function22(){\r\n");
      out.write("\tlocation.href=\"/doggybeta/views/notice/NewFile.html\"\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<input type=\"button\" value=\"검색하기\" onclick=\"function22();\">\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 지역검색 닫기 -->\r\n");
      out.write("<br><br>\r\n");
      out.write("<!-- 조건에 대한 결과 -->\r\n");
      out.write("<div id=\"detailmain\" style=\"width:1400px\" >\r\n");
      out.write("<div id=\"petinfo\"  style=\"float: left; width: 50%\">\r\n");
      out.write("상단 : 검색 결과 건수 조회\r\n");
      out.write("<hr>\r\n");
      out.write("<br>\r\n");
      out.write("\t<div id=\"detail\" style=\"overflow-x: hidden; overflow-y:scroll; height:550px;\">\r\n");
      out.write("\t\t<div id=\"detailtable\" style=\"float:left; width: 50%;\">\r\n");
      out.write("\t\t<table style=\"border: 1px solid #d2dee1; width: 300px;\">\t\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<div style=\"position: relative;\">\r\n");
      out.write("\t\t\t<img src=\"/doggybeta/resources/images/house.jpeg\" height=\"150px;\" width=\"100%;\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"position: relative; top: -40px;\">\r\n");
      out.write("\t\t\t<img src=\"/doggybeta/resources/images/dog1.jpg\" style=\"height: 60px; width : 60px; border-radius: 50px; border: 3px solid white\">\r\n");
      out.write("\t\t\t</div>\t\t\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<th>내 가족처럼 안전하게~</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>서울시 서초구</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>반려견 1마리</td>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td style=\"float:left;\">가격 : 50000원/1일</td> \r\n");
      out.write("\t\t<td style=\"float:right;\">평점 : \r\n");
      out.write("\t\t<span class=\"fa fa-star checked\"></span>\r\n");
      out.write("\t\t<span class=\"fa fa-star checked\"></span>\r\n");
      out.write("\t\t<span class=\"fa fa-star checked\"></span>\r\n");
      out.write("\t\t<span class=\"fa fa-star\"></span>\r\n");
      out.write("\t\t<span class=\"fa fa-star\"></span>\t\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr>\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"detailtable\" style=\"float:left; width: 50%;\">\r\n");
      out.write("\t\t<table style=\"border: 1px solid #d2dee1; width: 300px;\">\t\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<div style=\"position: relative;\">\r\n");
      out.write("\t\t\t<img src=\"/doggybeta/resources/images/house.jpeg\" height=\"150px;\" width=\"100%;\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"position: relative; top: -40px;\">\r\n");
      out.write("\t\t\t<img src=\"/doggybeta/resources/images/dog1.jpg\" style=\"height: 60px; width : 60px; border-radius: 50px; border: 3px solid white\">\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<th>내 가족처럼 안전하게~</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>서울시 서초구</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>반려견 1마리</td>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td style=\"float:left;\">가격 : 50000원/1일</td> \r\n");
      out.write("\t\t<td style=\"float:right;\">평점 : \r\n");
      out.write("\t\t<span class=\"fa fa-star checked\"></span>\r\n");
      out.write("\t\t<span class=\"fa fa-star checked\"></span>\r\n");
      out.write("\t\t<span class=\"fa fa-star checked\"></span>\r\n");
      out.write("\t\t<span class=\"fa fa-star\"></span>\r\n");
      out.write("\t\t<span class=\"fa fa-star\"></span>\t\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr>\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"detailtable\" style=\"float:left; width: 50%;\">\r\n");
      out.write("\t\t<table style=\"border: 1px solid #d2dee1; width: 300px;\">\t\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<div style=\"position: relative;\">\r\n");
      out.write("\t\t\t<img src=\"/doggybeta/resources/images/house.jpeg\" height=\"150px;\" width=\"100%;\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"position: relative; top: -40px;\">\r\n");
      out.write("\t\t\t<img src=\"/doggybeta/resources/images/dog1.jpg\" style=\"height: 60px; width : 60px; border-radius: 50px; border: 3px solid white\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<th>내 가족처럼 안전하게~</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>서울시 서초구</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>반려견 1마리</td>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td style=\"float:left;\">가격 : 50000원/1일</td> \r\n");
      out.write("\t\t<td style=\"float:right;\">평점 : \r\n");
      out.write("\t\t<span class=\"fa fa-star checked\"></span>\r\n");
      out.write("\t\t<span class=\"fa fa-star checked\"></span>\r\n");
      out.write("\t\t<span class=\"fa fa-star checked\"></span>\r\n");
      out.write("\t\t<span class=\"fa fa-star\"></span>\r\n");
      out.write("\t\t<span class=\"fa fa-star\"></span>\t\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr>\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"detailtable\" style=\"float:left; width: 50%;\">\r\n");
      out.write("\t\t<table style=\"border: 1px solid #d2dee1; width: 300px;\">\t\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<div style=\"position: relative;\">\r\n");
      out.write("\t\t\t<img src=\"/doggybeta/resources/images/house.jpeg\" height=\"150px;\" width=\"100%;\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"position: relative; top: -40px;\">\r\n");
      out.write("\t\t\t<img src=\"/doggybeta/resources/images/dog1.jpg\" style=\"height: 60px; width : 60px; border-radius: 50px; border: 3px solid white\">\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<th>내 가족처럼 안전하게~</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>서울시 서초구</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>반려견 1마리</td>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td style=\"float:left;\">가격 : 50000원/1일</td> \r\n");
      out.write("\t\t<td style=\"float:right;\">평점 : \r\n");
      out.write("\t\t<span class=\"fa fa-star checked\"></span>\r\n");
      out.write("\t\t<span class=\"fa fa-star checked\"></span>\r\n");
      out.write("\t\t<span class=\"fa fa-star checked\"></span>\r\n");
      out.write("\t\t<span class=\"fa fa-star\"></span>\r\n");
      out.write("\t\t<span class=\"fa fa-star\"></span>\t\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr>\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- detailinfo닫기 -->\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div style=\"float:left; width:50%;\">\r\n");
      out.write("지도출력\r\n");
      out.write("<hr>\r\n");
      out.write("<br>\r\n");
      out.write("<div id=\"map\" style=\"width:100%;height:550px;\"></div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=61e779cba5e3e9729c7fb3b2830dba72\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar mapContainer = document.getElementById('map'), // 지도를 표시할 div \r\n");
      out.write("    \tmapOption = { \r\n");
      out.write("        center: new daum.maps.LatLng(37.499274, 127.032963), // 지도의 중심좌표\r\n");
      out.write("        level: 3 // 지도의 확대 레벨\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("\tvar map = new daum.maps.Map(mapContainer, mapOption); // 지도를 생성합니다\r\n");
      out.write("\r\n");
      out.write("    // 마우스 드래그로 지도 이동 가능여부를 설정합니다\r\n");
      out.write("    map.setDraggable(true);  \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</div>\r\n");
      out.write("</div> \r\n");
      out.write("</div>\r\n");
      out.write("\t\t\r\n");
      out.write("<div id=\"footer\">");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title></title>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("\n");
      out.write("/* footer {\n");
      out.write("\ttext-align:center;\n");
      out.write("    bottom:0;\n");
      out.write("    width:120%;\n");
      out.write("    background:#ccc;\n");
      out.write("    margin-bottom:0;\n");
      out.write("    border-top-width: 0;\n");
      out.write("} */\n");
      out.write("/* footer{\n");
      out.write("\twidth:100%;\n");
      out.write("\theight:60px; \n");
      out.write("\tposition:absolute;\n");
      out.write("\tbottom:0; \n");
      out.write("\tleft:0;\n");
      out.write("\tbackground:#ccc;\n");
      out.write("\ttext-align:center;\n");
      out.write("} */\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<footer>\n");
      out.write("copyright@kh.org 2019-03-04 master : 홍길동 <br>\n");
      out.write("tel : 02-1234-5678, 서울시 강남구 역삼동 777, fax : 02-1111-2356\n");
      out.write("</footer>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
