/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-04-23 07:47:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class enrollPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tsection form table th {\r\n");
      out.write("\t\tbackground: orange;\r\n");
      out.write("\t\tcolor: navy;\r\n");
      out.write("\t\tfont-weight: bold;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../../../../resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction checkid() {\r\n");
      out.write("\t\t//서버로 입력된 아이디값을 전송해서 이미 있는 아이디인지 확인 요청. 이후 결과를 받아 사용여부 처리함.\r\n");
      out.write("\t\t//jQuery.ajax() 사용\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: '/testmb/chkid',\r\n");
      out.write("\t\t\ttype: 'post',\r\n");
      out.write("\t\t\tdata: {userid: $('#userid').val()}, \r\n");
      out.write("\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\tconsole.log(\"success\"+data);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(data==\"ok\"){\r\n");
      out.write("\t\t\t\t\talert('사용할 수 있는 아이디입니다.');\r\n");
      out.write("\t\t\t\t\t$('#username').focus();\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\talert('이미 사용중인 아이디입니다.\\n'+'다른 아이디를 입력해주세요');\r\n");
      out.write("\t\t\t\t\t$('#userid').select();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(jqXHR, textStatus, errorThrown) {\r\n");
      out.write("\t\t\t\tconsole.log(\"error : \"+jqXHR+\",\"+textStatus+\",\"+errorThrown);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn false; //클릭 이벤트 전달받음\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t//암호 확인입력상자의 focus가 사라졌을 때\r\n");
      out.write("\t\t$('#userpwd2').blur(function() {\r\n");
      out.write("\t\t\tconsole.log('포커스사라짐');\r\n");
      out.write("\t\t\tvar pwd1=$('#userpwd1').val();\r\n");
      out.write("\t\t\tvar pwd2=$('#userpwd2').val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(pwd1!=pwd2) {\r\n");
      out.write("\t\t\t\talert('암호가 일치하지 않습니다.\\n'+'다시 입력하세요');\r\n");
      out.write("\t\t\t\t$('#userpwd1').select();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\r\n");
      out.write("<section>\r\n");
      out.write("\t<h2 align=\"center\">회원가입페이지</h2><br>\r\n");
      out.write("\t<h5 align=\"center\">* 표시 항목은 필수입력 항목입니다.</h5>\r\n");
      out.write("\t<form action=\"minsert.do\" method=\"post\" enctype='multipart/form-data' onsubmit='return checkValidate1();'>\r\n");
      out.write("\t<table width=\"650\" align=\"center\">\r\n");
      out.write("\t<tr height=\"40\">\r\n");
      out.write("\t\t<th width=\"150\">*아이디</th>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"userid\" id=\"userid\" required/>\r\n");
      out.write("\t\t&nbsp; <button onclick=\"return checkid();\">중복확인</button></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=\"40\">\r\n");
      out.write("\t\t<th width=\"150\">*이름</th>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"username\" required id='username'/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=\"40\">\r\n");
      out.write("\t\t<th width=\"150\">*암호</th>\r\n");
      out.write("\t\t<td><input type=\"password\" name=\"userpwd\" id=\"userpwd1\" required/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=\"40\">\r\n");
      out.write("\t\t<th width=\"150\">*암호확인</th>\r\n");
      out.write("\t\t<td><input type=\"password\" id=\"userpwd2\" required/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=\"40\">\r\n");
      out.write("\t\t<th width=\"150\">*성별</th>\r\n");
      out.write("\t\t<td><input type=\"radio\" name=\"gender\" value=\"M\"/>남자 &nbsp;\r\n");
      out.write("\t\t\t<input type=\"radio\" name='gender' value='F'/>여자\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=\"40\">\r\n");
      out.write("\t\t<th width=\"150\">*나이</th>\r\n");
      out.write("\t\t<td><input type=\"number\" name='age' min='19' max='100' required/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=\"40\">\r\n");
      out.write("\t\t<th width=\"150\">전화번호</th>\r\n");
      out.write("\t\t<td><input type='tel' name='phone'/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=\"40\">\r\n");
      out.write("\t\t<th width=\"150\">이메일</th>\r\n");
      out.write("\t\t<td><input type='email' name='email'/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=\"40\">\r\n");
      out.write("\t\t<th width=\"150\">취미</th>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width='150'><input type='checkbox' name='hobby' value='game'/>게임</td>\r\n");
      out.write("\t\t\t\t<td width='150'><input type='checkbox' name='hobby' value='music'/>음악감상</td>\r\n");
      out.write("\t\t\t\t<td width='150'><input type='checkbox' name='hobby' value='reading'/>독서</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width='150'><input type='checkbox' name='hobby' value='climb'/>등산</td>\r\n");
      out.write("\t\t\t\t<td width='150'><input type='checkbox' name='hobby' value='sport'/>스포츠</td>\r\n");
      out.write("\t\t\t\t<td width='150'><input type='checkbox' name='hobby' value='movie'/>영화</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width='150'><input type='checkbox' name='hobby' value='travle'/>여행</td>\r\n");
      out.write("\t\t\t\t<td width='150'><input type='checkbox' name='hobby' value='sing'/>노래</td>\r\n");
      out.write("\t\t\t\t<td width='150'><input type='checkbox' name='hobby' value='aso'/>기타등등</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=\"40\">\r\n");
      out.write("\t\t<th width=\"150\">하고싶은 말</th>\r\n");
      out.write("\t\t<td><textarea name='etc' rows='3' cols='30'></textarea></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>프로필사진</th>\r\n");
      out.write("\t\t<td><input type='file' name='photo'/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=\"40\">\r\n");
      out.write("\t\t<th colspan=\"2\">가입하기\r\n");
      out.write("\t\t<input type=\"submit\" value=\"가입하기\"/>&nbsp;\r\n");
      out.write("\t\t<input type=\"reset\" value=\"작성취소\"/>&nbsp;\r\n");
      out.write("\t\t<a href=\"/testmb/index.jsp\">시작페이지로 이동</a>\r\n");
      out.write("\t\t</th>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
